package org.acme.model;

import java.util.List;
import java.util.ArrayList;

public class Speciality {
    public static List<String> speciality = new ArrayList<String>();
    static {
        speciality.add("Addiction Medicine");
        speciality.add("Allergy");
        speciality.add("Anesthesiology");
        speciality.add("Breast Surgery");
        speciality.add("Cardiothoracic Surgery");
        speciality.add("Cardiology");
        speciality.add("Cosmetology");
        speciality.add("Cosmetic Surgery");
        speciality.add("Critical Care");
        speciality.add("Dentistry");
        speciality.add("Dentistry &amp; Maxillofacial Surgery");
        speciality.add("Dermatology (Skin)");
        speciality.add("Diabetology");
        speciality.add("Emergency Medicine");
        speciality.add("Endocrinology");
        speciality.add("ENT (Otolaryngology)");
        speciality.add("ENT and Head &amp; Neck Surgery");
        speciality.add("Fetal Medicine");
        speciality.add("Gastroenterology");
        speciality.add("General Medicine");
        speciality.add("General Surgery");
        speciality.add("Gynecology");
        speciality.add("Hematology");
        speciality.add("Hepatobiliary Surgery");
        speciality.add("Hepatology");
        speciality.add("Infectious Diseases");
        speciality.add("Internal Medicine");
        speciality.add("Interventional Radiology");
        speciality.add("Laparoscopic Surgery");
        speciality.add("Liver Transplant &amp; Hepatobiliary Surgery");
        speciality.add("Maxillofacial Surgery");
        speciality.add("Medical Oncology");
        speciality.add("Neonatology");
        speciality.add("Nephrology");
        speciality.add("Neurology");
        speciality.add("Neurosurgery");
        speciality.add("Obstetrics and Gynecology");
        speciality.add("Oncology");
        speciality.add("Ophthalmology");
        speciality.add("Orthodontics");
        speciality.add("Orthopedics &amp; Traumatology");
        speciality.add("Pathology");
        speciality.add("Pain Management");
        speciality.add("Pediatric Cardiothoracic Surgery");
        speciality.add("Pediatric Critical Care");
        speciality.add("Pediatric Dentistry");
        speciality.add("Pediatric Endocrinology");
        speciality.add("Pediatric Hematology &amp; Oncology");
        speciality.add("Pediatric ENT");
        speciality.add("Pediatric Nephrology");
        speciality.add("Pediatric Neurology");
        speciality.add("Pediatric Surgery");
        speciality.add("Pediatrics");
        speciality.add("Plastic Surgery");
        speciality.add("Plastic Surgery &amp; Cosmetic Surgery");
        speciality.add("Psychiatry");
        speciality.add("Pulmonology");
        speciality.add("Radiation Oncology");
        speciality.add("Radio-Diagnosis");
        speciality.add("Radiology");
        speciality.add("Rheumatology");
        speciality.add("Sleep Medicine");
        speciality.add("Spine Surgery");
        speciality.add("Surgical Gastroenterology");
        speciality.add("Surgical Oncology");
        speciality.add("Urology");
        speciality.add("Vascular Surgery");
        speciality.add("Andrology");
        speciality.add("Neuropsychology");
        speciality.add("Cardiovascular Surgery");
        speciality.add("Gastro Surgery");
        speciality.add("Interventional Cardiology");
        speciality.add("Interventional Neuroradiology");
        speciality.add("Robotic Surgery");
        speciality.add("Orthopedics");
        speciality.add("Bariatric Surgery");
        speciality.add("Liver Transplant");
        speciality.add("Kidney Transplantation");
        speciality.add("Radiology &amp; Imageology");
        speciality.add("Neuro Psychiatry");
        speciality.add("Pediatric Dermatology");
        speciality.add("Venereology");
        speciality.add("Trichology");
        speciality.add("Orthopedic Surgery");
        speciality.add("Psychology");
        speciality.add("Pediatric Orthopedics");
        speciality.add("Knee Surgery");
        speciality.add("Hip Replacement Surgery");
        speciality.add("Traumatology");
        speciality.add("Hemato Oncology");
        speciality.add("Joint Replacement Surgery");
        speciality.add("Tummy Tuck Surgery");
        speciality.add("Spine and Joint Replacement");
        speciality.add("Trauma Surgery");
        speciality.add("Addiction Psychiatry");
        speciality.add("Adolescent Psychiatry");
        speciality.add("Child Psychiatry");
        speciality.add("Geriatric Psychiatry");
        speciality.add("Adult Psychiatry");
        speciality.add("Neonatal Surgery");
        speciality.add("Pediatric Pulmonology");
        speciality.add("EndoUrology");
        speciality.add("Renal Transplant");
        speciality.add("Cosmetic Dermatology");
        speciality.add("General &amp; Laparoscopic Surgery");
        speciality.add("Pediatric Cardiac Surgery");
        speciality.add("Gynae Oncology");
        speciality.add("Gastrointestinal Surgery");
        speciality.add("Preventive Oncology");
        speciality.add("UroSurgery");
        speciality.add("Electrophysiology");
        speciality.add("Pediatric Oncology");
        speciality.add("IVF &amp; Infertility");
        speciality.add("Pediatric Neuro Rehabilitation");
        speciality.add("Uro &amp; Gynaec Oncology");
        speciality.add("Cancer Chemotherapy");
        speciality.add("Cancer Radiation Therapy");
        speciality.add("Neuro Oncology");
        speciality.add("Orthopedic Oncology");
        speciality.add("HIV Medicine");
    }

    
} 